trigger:
- devops
  
pool: gfc

variables:
  imageName: 'hello-gin'
  dockerRegistryServiceConnection: 'acr-for-canary'
  imageRepository: 'hello-gin'
  containerRegistry: 'registryforadopoc.azurecr.io'
  tag: '$(Build.BuildId)'
  ### CD
stages:
  - stage: DeployCanary
    displayName: Deploy canary
    jobs:
      - deployment: Deploycanary
        displayName: Deploy canary
        environment: 'dh-aks.canary-test'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: 'deploy'
                    strategy: 'canary'
                    percentage: 10
                    manifests: |
                      $(System.DefaultWorkingDirectory)/manifests-canary/deployment-blue.yml
                      $(System.DefaultWorkingDirectory)/manifests-canary/service-blue.yml
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'
  - stage: PromoteRejectCanary
    displayName: Promote or Reject canary
    dependsOn: DeployCanary
    condition: succeeded()
    jobs:
      - deployment: PromoteCanary
        displayName: Promote Canary
        environment: 'dh-aks.canary-test'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: promote canary
                  inputs:
                    action: 'promote'
                    strategy: 'canary'
                    manifests: '$(System.DefaultWorkingDirectory)/manifests-canary/*'
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'
  - stage: RejectCanary
    displayName: Reject canary
    dependsOn: PromoteRejectCanary
    condition: failed()
    jobs:
      - deployment: RejectCanary
        displayName: Reject Canary
        environment: 'dh-aks.canary-test'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: reject canary
                  inputs:
                    action: 'reject'
                    strategy: 'canary'
                    manifests: '$(System.DefaultWorkingDirectory)/manifests-canary/*'
  - stage: DeployCanary25
    displayName: Deploy canary

    jobs:
      - deployment: Deploycanary
        displayName: Deploy canary
        environment: 'dh-aks.canary-test'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: 'deploy'
                    strategy: 'canary'
                    percentage: 25
                    manifests: |
                      $(System.DefaultWorkingDirectory)/manifests-canary/deployment-blue.yml
                      $(System.DefaultWorkingDirectory)/manifests-canary/service-blue.yml
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'
  - stage: PromoteRejectCanary25
    displayName: 25% Promote or Reject canary
    dependsOn: DeployCanary
    condition: succeeded()
    jobs:
      - deployment: PromoteCanary
        displayName: 25% Promote Canary
        environment: 'dh-aks.canary-test'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: promote canary
                  inputs:
                    action: 'promote'
                    strategy: 'canary'
                    manifests: '$(System.DefaultWorkingDirectory)/manifests-canary/*'
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'
  - stage: RejectCanary25
    displayName: 25% Reject canary
    dependsOn: PromoteRejectCanary
    condition: failed()
    jobs:
      - deployment: RejectCanary
        displayName: 25% Reject Canary
        environment: 'dh-aks.canary-test'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: reject canary
                  inputs:
                    action: 'reject'
                    strategy: 'canary'
                    manifests: '$(System.DefaultWorkingDirectory)/manifests-canary/*'